//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol__TestDemo_
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialType
    {
        public int material_type_id { get; set; }
        public string material_type_name { get; set; }
        public decimal material_brak_percent { get; set; }
    }
}
