//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol__TestDemo_
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProduct
    {
        public int partner_product_id { get; set; }
        public int product { get; set; }
        public int partner { get; set; }
        public int product_quantity { get; set; }
        public System.DateTime sale_date { get; set; }
    
        public virtual Partner Partner1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
