//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol__TestDemo_
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Partner
    {
        public Partner()
        {
            this.PartnerProduct = new HashSet<PartnerProduct>();
        }

        public int partner_id { get; set; }
        public string partner_name { get; set; }
        public int partner_type { get; set; }
        public Nullable<int> partner_rating { get; set; }
        public string partner_address { get; set; }
        public string partner_inn { get; set; }
        public string partner_director_fio { get; set; }
        public string partner_number_phone { get; set; }
        public string partner_email { get; set; }

        public virtual PartnerType PartnerType { get; set; }
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }

        public int discount
        {
            get
            {
                var totalSales = this.PartnerProduct.Sum(pp => pp.product_quantity);

                if (totalSales > 10000 && totalSales < 50000)
                {
                    return 5;
                }

                else if (totalSales > 50000 && totalSales < 30000)
                {
                    return 10;
                }

                else if (totalSales > 300000)
                {
                    return 15;
                }

                return 0;
            }
        }
    }
}
