//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol__TestDemo_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public ProductType()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int product_type_id { get; set; }
        public string product_type_name { get; set; }
        public Nullable<decimal> product_type_koef { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
